// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9IlkcllbNY6d10XB0dH8JcYtvsweo5_4',
    appId: '1:270573902154:web:1329e58e467987572f49b3',
    messagingSenderId: '270573902154',
    projectId: 'poeage-hub',
    authDomain: 'poeage-hub.firebaseapp.com',
    storageBucket: 'poeage-hub.firebasestorage.app',
    measurementId: 'G-NCS5GFMS0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC55hcVdkjLnDL7FBiVkHRXCTq75EwN0Ro',
    appId: '1:270573902154:android:f3af52e9e8fe26932f49b3',
    messagingSenderId: '270573902154',
    projectId: 'poeage-hub',
    storageBucket: 'poeage-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlfyhZdYuzQxoWxIvXpFnf69nrokNsp0s',
    appId: '1:270573902154:ios:fa77098f2096bfad2f49b3',
    messagingSenderId: '270573902154',
    projectId: 'poeage-hub',
    storageBucket: 'poeage-hub.firebasestorage.app',
    androidClientId: '270573902154-4mg7nq9mn5l55trgmueh7g9m0vujrthb.apps.googleusercontent.com',
    iosClientId: '270573902154-33svohd5gmcaut1gqhm39v5jva1t3cq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.poeagehubUserInterface',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlfyhZdYuzQxoWxIvXpFnf69nrokNsp0s',
    appId: '1:270573902154:ios:fa77098f2096bfad2f49b3',
    messagingSenderId: '270573902154',
    projectId: 'poeage-hub',
    storageBucket: 'poeage-hub.firebasestorage.app',
    androidClientId: '270573902154-4mg7nq9mn5l55trgmueh7g9m0vujrthb.apps.googleusercontent.com',
    iosClientId: '270573902154-33svohd5gmcaut1gqhm39v5jva1t3cq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.poeagehubUserInterface',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzf3nWgRSYEJawJYLpxjNk8biK4za81nE',
    appId: '1:270573902154:web:8abe997ae37320e02f49b3',
    messagingSenderId: '270573902154',
    projectId: 'poeage-hub',
    authDomain: 'poeage-hub.firebaseapp.com',
    storageBucket: 'poeage-hub.firebasestorage.app',
    measurementId: 'G-SZ0NENRW49',
  );
}
